package com.chinadovey.power.webapps.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CdmeterCacheDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public CdmeterCacheDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEcuIdIsNull() {
            addCriterion("ecu_id is null");
            return (Criteria) this;
        }

        public Criteria andEcuIdIsNotNull() {
            addCriterion("ecu_id is not null");
            return (Criteria) this;
        }

        public Criteria andEcuIdEqualTo(Integer value) {
            addCriterion("ecu_id =", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdNotEqualTo(Integer value) {
            addCriterion("ecu_id <>", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdGreaterThan(Integer value) {
            addCriterion("ecu_id >", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ecu_id >=", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdLessThan(Integer value) {
            addCriterion("ecu_id <", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdLessThanOrEqualTo(Integer value) {
            addCriterion("ecu_id <=", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdIn(List<Integer> values) {
            addCriterion("ecu_id in", values, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdNotIn(List<Integer> values) {
            addCriterion("ecu_id not in", values, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdBetween(Integer value1, Integer value2) {
            addCriterion("ecu_id between", value1, value2, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ecu_id not between", value1, value2, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEquiIdIsNull() {
            addCriterion("equi_id is null");
            return (Criteria) this;
        }

        public Criteria andEquiIdIsNotNull() {
            addCriterion("equi_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquiIdEqualTo(Long value) {
            addCriterion("equi_id =", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdNotEqualTo(Long value) {
            addCriterion("equi_id <>", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdGreaterThan(Long value) {
            addCriterion("equi_id >", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("equi_id >=", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdLessThan(Long value) {
            addCriterion("equi_id <", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdLessThanOrEqualTo(Long value) {
            addCriterion("equi_id <=", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdIn(List<Long> values) {
            addCriterion("equi_id in", values, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdNotIn(List<Long> values) {
            addCriterion("equi_id not in", values, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdBetween(Long value1, Long value2) {
            addCriterion("equi_id between", value1, value2, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdNotBetween(Long value1, Long value2) {
            addCriterion("equi_id not between", value1, value2, "equiId");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIsNull() {
            addCriterion("collect_time is null");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIsNotNull() {
            addCriterion("collect_time is not null");
            return (Criteria) this;
        }

        public Criteria andCollectTimeEqualTo(Date value) {
            addCriterion("collect_time =", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotEqualTo(Date value) {
            addCriterion("collect_time <>", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeGreaterThan(Date value) {
            addCriterion("collect_time >", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("collect_time >=", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeLessThan(Date value) {
            addCriterion("collect_time <", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeLessThanOrEqualTo(Date value) {
            addCriterion("collect_time <=", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIn(List<Date> values) {
            addCriterion("collect_time in", values, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotIn(List<Date> values) {
            addCriterion("collect_time not in", values, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeBetween(Date value1, Date value2) {
            addCriterion("collect_time between", value1, value2, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotBetween(Date value1, Date value2) {
            addCriterion("collect_time not between", value1, value2, "collectTime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table power_cache_data
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 01 10:25:00 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table power_cache_data
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}