package com.chinadovey.power.webapps.pojo;

import java.util.Date;

public class CdmeterCacheData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cache_data.id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cache_data.ecu_id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    private Integer ecuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cache_data.equi_id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    private Long equiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cache_data.collect_time
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cache_data.type
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cache_data.id
     *
     * @return the value of power_cache_data.id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cache_data.id
     *
     * @param id the value for power_cache_data.id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cache_data.ecu_id
     *
     * @return the value of power_cache_data.ecu_id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Integer getEcuId() {
        return ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cache_data.ecu_id
     *
     * @param ecuId the value for power_cache_data.ecu_id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setEcuId(Integer ecuId) {
        this.ecuId = ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cache_data.equi_id
     *
     * @return the value of power_cache_data.equi_id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Long getEquiId() {
        return equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cache_data.equi_id
     *
     * @param equiId the value for power_cache_data.equi_id
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setEquiId(Long equiId) {
        this.equiId = equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cache_data.collect_time
     *
     * @return the value of power_cache_data.collect_time
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cache_data.collect_time
     *
     * @param collectTime the value for power_cache_data.collect_time
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cache_data.type
     *
     * @return the value of power_cache_data.type
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cache_data.type
     *
     * @param type the value for power_cache_data.type
     *
     * @mbggenerated Tue Nov 01 10:25:00 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}