package com.chinadovey.power.webapps.pojo;

import java.util.Date;

public class PowerCdmeterdataRealtime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Integer ecuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Long equiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Integer equiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_fr
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiFr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ps
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ps_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPsA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ps_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPsB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ps_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPsC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_qs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiQs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_qs_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiQsA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_qs_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiQsB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_qs_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiQsC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_pfs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_pfs_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPfsA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_pfs_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPfsB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_pfs_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPfsC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ua
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiUa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ub
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiUb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_uc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiUc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_uab
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiUab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ubc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiUbc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_uca
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiUca;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ia
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiIa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ib
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiIb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_ic
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiIc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_thd_ia
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThdIa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_thd_ib
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThdIb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_thd_ic
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThdIc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_thd_ua
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThdUa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_thd_ub
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThdUb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.equi_thd_uc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThdUc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Date saveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.id
     *
     * @return the value of power_cdmeterdata_realtime.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.id
     *
     * @param id the value for power_cdmeterdata_realtime.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.ecu_id
     *
     * @return the value of power_cdmeterdata_realtime.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Integer getEcuId() {
        return ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.ecu_id
     *
     * @param ecuId the value for power_cdmeterdata_realtime.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEcuId(Integer ecuId) {
        this.ecuId = ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_id
     *
     * @return the value of power_cdmeterdata_realtime.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Long getEquiId() {
        return equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_id
     *
     * @param equiId the value for power_cdmeterdata_realtime.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiId(Long equiId) {
        this.equiId = equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_status
     *
     * @return the value of power_cdmeterdata_realtime.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Integer getEquiStatus() {
        return equiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_status
     *
     * @param equiStatus the value for power_cdmeterdata_realtime.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiStatus(Integer equiStatus) {
        this.equiStatus = equiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_fr
     *
     * @return the value of power_cdmeterdata_realtime.equi_fr
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiFr() {
        return equiFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_fr
     *
     * @param equiFr the value for power_cdmeterdata_realtime.equi_fr
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiFr(Double equiFr) {
        this.equiFr = equiFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ps
     *
     * @return the value of power_cdmeterdata_realtime.equi_ps
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPs() {
        return equiPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ps
     *
     * @param equiPs the value for power_cdmeterdata_realtime.equi_ps
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPs(Double equiPs) {
        this.equiPs = equiPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ps_a
     *
     * @return the value of power_cdmeterdata_realtime.equi_ps_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPsA() {
        return equiPsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ps_a
     *
     * @param equiPsA the value for power_cdmeterdata_realtime.equi_ps_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPsA(Double equiPsA) {
        this.equiPsA = equiPsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ps_b
     *
     * @return the value of power_cdmeterdata_realtime.equi_ps_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPsB() {
        return equiPsB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ps_b
     *
     * @param equiPsB the value for power_cdmeterdata_realtime.equi_ps_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPsB(Double equiPsB) {
        this.equiPsB = equiPsB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ps_c
     *
     * @return the value of power_cdmeterdata_realtime.equi_ps_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPsC() {
        return equiPsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ps_c
     *
     * @param equiPsC the value for power_cdmeterdata_realtime.equi_ps_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPsC(Double equiPsC) {
        this.equiPsC = equiPsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_qs
     *
     * @return the value of power_cdmeterdata_realtime.equi_qs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiQs() {
        return equiQs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_qs
     *
     * @param equiQs the value for power_cdmeterdata_realtime.equi_qs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiQs(Double equiQs) {
        this.equiQs = equiQs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_qs_a
     *
     * @return the value of power_cdmeterdata_realtime.equi_qs_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiQsA() {
        return equiQsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_qs_a
     *
     * @param equiQsA the value for power_cdmeterdata_realtime.equi_qs_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiQsA(Double equiQsA) {
        this.equiQsA = equiQsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_qs_b
     *
     * @return the value of power_cdmeterdata_realtime.equi_qs_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiQsB() {
        return equiQsB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_qs_b
     *
     * @param equiQsB the value for power_cdmeterdata_realtime.equi_qs_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiQsB(Double equiQsB) {
        this.equiQsB = equiQsB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_qs_c
     *
     * @return the value of power_cdmeterdata_realtime.equi_qs_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiQsC() {
        return equiQsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_qs_c
     *
     * @param equiQsC the value for power_cdmeterdata_realtime.equi_qs_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiQsC(Double equiQsC) {
        this.equiQsC = equiQsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_pfs
     *
     * @return the value of power_cdmeterdata_realtime.equi_pfs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPfs() {
        return equiPfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_pfs
     *
     * @param equiPfs the value for power_cdmeterdata_realtime.equi_pfs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPfs(Double equiPfs) {
        this.equiPfs = equiPfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_pfs_a
     *
     * @return the value of power_cdmeterdata_realtime.equi_pfs_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPfsA() {
        return equiPfsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_pfs_a
     *
     * @param equiPfsA the value for power_cdmeterdata_realtime.equi_pfs_a
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPfsA(Double equiPfsA) {
        this.equiPfsA = equiPfsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_pfs_b
     *
     * @return the value of power_cdmeterdata_realtime.equi_pfs_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPfsB() {
        return equiPfsB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_pfs_b
     *
     * @param equiPfsB the value for power_cdmeterdata_realtime.equi_pfs_b
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPfsB(Double equiPfsB) {
        this.equiPfsB = equiPfsB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_pfs_c
     *
     * @return the value of power_cdmeterdata_realtime.equi_pfs_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPfsC() {
        return equiPfsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_pfs_c
     *
     * @param equiPfsC the value for power_cdmeterdata_realtime.equi_pfs_c
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPfsC(Double equiPfsC) {
        this.equiPfsC = equiPfsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ua
     *
     * @return the value of power_cdmeterdata_realtime.equi_ua
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiUa() {
        return equiUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ua
     *
     * @param equiUa the value for power_cdmeterdata_realtime.equi_ua
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiUa(Double equiUa) {
        this.equiUa = equiUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ub
     *
     * @return the value of power_cdmeterdata_realtime.equi_ub
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiUb() {
        return equiUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ub
     *
     * @param equiUb the value for power_cdmeterdata_realtime.equi_ub
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiUb(Double equiUb) {
        this.equiUb = equiUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_uc
     *
     * @return the value of power_cdmeterdata_realtime.equi_uc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiUc() {
        return equiUc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_uc
     *
     * @param equiUc the value for power_cdmeterdata_realtime.equi_uc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiUc(Double equiUc) {
        this.equiUc = equiUc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_uab
     *
     * @return the value of power_cdmeterdata_realtime.equi_uab
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiUab() {
        return equiUab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_uab
     *
     * @param equiUab the value for power_cdmeterdata_realtime.equi_uab
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiUab(Double equiUab) {
        this.equiUab = equiUab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ubc
     *
     * @return the value of power_cdmeterdata_realtime.equi_ubc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiUbc() {
        return equiUbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ubc
     *
     * @param equiUbc the value for power_cdmeterdata_realtime.equi_ubc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiUbc(Double equiUbc) {
        this.equiUbc = equiUbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_uca
     *
     * @return the value of power_cdmeterdata_realtime.equi_uca
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiUca() {
        return equiUca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_uca
     *
     * @param equiUca the value for power_cdmeterdata_realtime.equi_uca
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiUca(Double equiUca) {
        this.equiUca = equiUca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ia
     *
     * @return the value of power_cdmeterdata_realtime.equi_ia
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiIa() {
        return equiIa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ia
     *
     * @param equiIa the value for power_cdmeterdata_realtime.equi_ia
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiIa(Double equiIa) {
        this.equiIa = equiIa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ib
     *
     * @return the value of power_cdmeterdata_realtime.equi_ib
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiIb() {
        return equiIb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ib
     *
     * @param equiIb the value for power_cdmeterdata_realtime.equi_ib
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiIb(Double equiIb) {
        this.equiIb = equiIb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_ic
     *
     * @return the value of power_cdmeterdata_realtime.equi_ic
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiIc() {
        return equiIc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_ic
     *
     * @param equiIc the value for power_cdmeterdata_realtime.equi_ic
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiIc(Double equiIc) {
        this.equiIc = equiIc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_thd_ia
     *
     * @return the value of power_cdmeterdata_realtime.equi_thd_ia
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThdIa() {
        return equiThdIa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_thd_ia
     *
     * @param equiThdIa the value for power_cdmeterdata_realtime.equi_thd_ia
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThdIa(Double equiThdIa) {
        this.equiThdIa = equiThdIa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_thd_ib
     *
     * @return the value of power_cdmeterdata_realtime.equi_thd_ib
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThdIb() {
        return equiThdIb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_thd_ib
     *
     * @param equiThdIb the value for power_cdmeterdata_realtime.equi_thd_ib
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThdIb(Double equiThdIb) {
        this.equiThdIb = equiThdIb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_thd_ic
     *
     * @return the value of power_cdmeterdata_realtime.equi_thd_ic
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThdIc() {
        return equiThdIc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_thd_ic
     *
     * @param equiThdIc the value for power_cdmeterdata_realtime.equi_thd_ic
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThdIc(Double equiThdIc) {
        this.equiThdIc = equiThdIc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_thd_ua
     *
     * @return the value of power_cdmeterdata_realtime.equi_thd_ua
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThdUa() {
        return equiThdUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_thd_ua
     *
     * @param equiThdUa the value for power_cdmeterdata_realtime.equi_thd_ua
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThdUa(Double equiThdUa) {
        this.equiThdUa = equiThdUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_thd_ub
     *
     * @return the value of power_cdmeterdata_realtime.equi_thd_ub
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThdUb() {
        return equiThdUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_thd_ub
     *
     * @param equiThdUb the value for power_cdmeterdata_realtime.equi_thd_ub
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThdUb(Double equiThdUb) {
        this.equiThdUb = equiThdUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.equi_thd_uc
     *
     * @return the value of power_cdmeterdata_realtime.equi_thd_uc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThdUc() {
        return equiThdUc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.equi_thd_uc
     *
     * @param equiThdUc the value for power_cdmeterdata_realtime.equi_thd_uc
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThdUc(Double equiThdUc) {
        this.equiThdUc = equiThdUc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.collect_time
     *
     * @return the value of power_cdmeterdata_realtime.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.collect_time
     *
     * @param collectTime the value for power_cdmeterdata_realtime.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime.save_time
     *
     * @return the value of power_cdmeterdata_realtime.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime.save_time
     *
     * @param saveTime the value for power_cdmeterdata_realtime.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }
}