package com.chinadovey.power.webapps.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PowerCdmeterdataRealtimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public PowerCdmeterdataRealtimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEcuIdIsNull() {
            addCriterion("ecu_id is null");
            return (Criteria) this;
        }

        public Criteria andEcuIdIsNotNull() {
            addCriterion("ecu_id is not null");
            return (Criteria) this;
        }

        public Criteria andEcuIdEqualTo(Integer value) {
            addCriterion("ecu_id =", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdNotEqualTo(Integer value) {
            addCriterion("ecu_id <>", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdGreaterThan(Integer value) {
            addCriterion("ecu_id >", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ecu_id >=", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdLessThan(Integer value) {
            addCriterion("ecu_id <", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdLessThanOrEqualTo(Integer value) {
            addCriterion("ecu_id <=", value, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdIn(List<Integer> values) {
            addCriterion("ecu_id in", values, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdNotIn(List<Integer> values) {
            addCriterion("ecu_id not in", values, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdBetween(Integer value1, Integer value2) {
            addCriterion("ecu_id between", value1, value2, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEcuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ecu_id not between", value1, value2, "ecuId");
            return (Criteria) this;
        }

        public Criteria andEquiIdIsNull() {
            addCriterion("equi_id is null");
            return (Criteria) this;
        }

        public Criteria andEquiIdIsNotNull() {
            addCriterion("equi_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquiIdEqualTo(Long value) {
            addCriterion("equi_id =", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdNotEqualTo(Long value) {
            addCriterion("equi_id <>", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdGreaterThan(Long value) {
            addCriterion("equi_id >", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("equi_id >=", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdLessThan(Long value) {
            addCriterion("equi_id <", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdLessThanOrEqualTo(Long value) {
            addCriterion("equi_id <=", value, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdIn(List<Long> values) {
            addCriterion("equi_id in", values, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdNotIn(List<Long> values) {
            addCriterion("equi_id not in", values, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdBetween(Long value1, Long value2) {
            addCriterion("equi_id between", value1, value2, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiIdNotBetween(Long value1, Long value2) {
            addCriterion("equi_id not between", value1, value2, "equiId");
            return (Criteria) this;
        }

        public Criteria andEquiStatusIsNull() {
            addCriterion("equi_status is null");
            return (Criteria) this;
        }

        public Criteria andEquiStatusIsNotNull() {
            addCriterion("equi_status is not null");
            return (Criteria) this;
        }

        public Criteria andEquiStatusEqualTo(Integer value) {
            addCriterion("equi_status =", value, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusNotEqualTo(Integer value) {
            addCriterion("equi_status <>", value, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusGreaterThan(Integer value) {
            addCriterion("equi_status >", value, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("equi_status >=", value, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusLessThan(Integer value) {
            addCriterion("equi_status <", value, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusLessThanOrEqualTo(Integer value) {
            addCriterion("equi_status <=", value, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusIn(List<Integer> values) {
            addCriterion("equi_status in", values, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusNotIn(List<Integer> values) {
            addCriterion("equi_status not in", values, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusBetween(Integer value1, Integer value2) {
            addCriterion("equi_status between", value1, value2, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("equi_status not between", value1, value2, "equiStatus");
            return (Criteria) this;
        }

        public Criteria andEquiFrIsNull() {
            addCriterion("equi_fr is null");
            return (Criteria) this;
        }

        public Criteria andEquiFrIsNotNull() {
            addCriterion("equi_fr is not null");
            return (Criteria) this;
        }

        public Criteria andEquiFrEqualTo(Double value) {
            addCriterion("equi_fr =", value, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrNotEqualTo(Double value) {
            addCriterion("equi_fr <>", value, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrGreaterThan(Double value) {
            addCriterion("equi_fr >", value, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_fr >=", value, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrLessThan(Double value) {
            addCriterion("equi_fr <", value, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrLessThanOrEqualTo(Double value) {
            addCriterion("equi_fr <=", value, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrIn(List<Double> values) {
            addCriterion("equi_fr in", values, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrNotIn(List<Double> values) {
            addCriterion("equi_fr not in", values, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrBetween(Double value1, Double value2) {
            addCriterion("equi_fr between", value1, value2, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiFrNotBetween(Double value1, Double value2) {
            addCriterion("equi_fr not between", value1, value2, "equiFr");
            return (Criteria) this;
        }

        public Criteria andEquiPsIsNull() {
            addCriterion("equi_ps is null");
            return (Criteria) this;
        }

        public Criteria andEquiPsIsNotNull() {
            addCriterion("equi_ps is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPsEqualTo(Double value) {
            addCriterion("equi_ps =", value, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsNotEqualTo(Double value) {
            addCriterion("equi_ps <>", value, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsGreaterThan(Double value) {
            addCriterion("equi_ps >", value, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ps >=", value, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsLessThan(Double value) {
            addCriterion("equi_ps <", value, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsLessThanOrEqualTo(Double value) {
            addCriterion("equi_ps <=", value, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsIn(List<Double> values) {
            addCriterion("equi_ps in", values, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsNotIn(List<Double> values) {
            addCriterion("equi_ps not in", values, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsBetween(Double value1, Double value2) {
            addCriterion("equi_ps between", value1, value2, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsNotBetween(Double value1, Double value2) {
            addCriterion("equi_ps not between", value1, value2, "equiPs");
            return (Criteria) this;
        }

        public Criteria andEquiPsAIsNull() {
            addCriterion("equi_ps_a is null");
            return (Criteria) this;
        }

        public Criteria andEquiPsAIsNotNull() {
            addCriterion("equi_ps_a is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPsAEqualTo(Double value) {
            addCriterion("equi_ps_a =", value, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsANotEqualTo(Double value) {
            addCriterion("equi_ps_a <>", value, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsAGreaterThan(Double value) {
            addCriterion("equi_ps_a >", value, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsAGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ps_a >=", value, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsALessThan(Double value) {
            addCriterion("equi_ps_a <", value, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsALessThanOrEqualTo(Double value) {
            addCriterion("equi_ps_a <=", value, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsAIn(List<Double> values) {
            addCriterion("equi_ps_a in", values, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsANotIn(List<Double> values) {
            addCriterion("equi_ps_a not in", values, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsABetween(Double value1, Double value2) {
            addCriterion("equi_ps_a between", value1, value2, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsANotBetween(Double value1, Double value2) {
            addCriterion("equi_ps_a not between", value1, value2, "equiPsA");
            return (Criteria) this;
        }

        public Criteria andEquiPsBIsNull() {
            addCriterion("equi_ps_b is null");
            return (Criteria) this;
        }

        public Criteria andEquiPsBIsNotNull() {
            addCriterion("equi_ps_b is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPsBEqualTo(Double value) {
            addCriterion("equi_ps_b =", value, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBNotEqualTo(Double value) {
            addCriterion("equi_ps_b <>", value, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBGreaterThan(Double value) {
            addCriterion("equi_ps_b >", value, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ps_b >=", value, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBLessThan(Double value) {
            addCriterion("equi_ps_b <", value, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBLessThanOrEqualTo(Double value) {
            addCriterion("equi_ps_b <=", value, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBIn(List<Double> values) {
            addCriterion("equi_ps_b in", values, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBNotIn(List<Double> values) {
            addCriterion("equi_ps_b not in", values, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBBetween(Double value1, Double value2) {
            addCriterion("equi_ps_b between", value1, value2, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsBNotBetween(Double value1, Double value2) {
            addCriterion("equi_ps_b not between", value1, value2, "equiPsB");
            return (Criteria) this;
        }

        public Criteria andEquiPsCIsNull() {
            addCriterion("equi_ps_c is null");
            return (Criteria) this;
        }

        public Criteria andEquiPsCIsNotNull() {
            addCriterion("equi_ps_c is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPsCEqualTo(Double value) {
            addCriterion("equi_ps_c =", value, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCNotEqualTo(Double value) {
            addCriterion("equi_ps_c <>", value, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCGreaterThan(Double value) {
            addCriterion("equi_ps_c >", value, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ps_c >=", value, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCLessThan(Double value) {
            addCriterion("equi_ps_c <", value, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCLessThanOrEqualTo(Double value) {
            addCriterion("equi_ps_c <=", value, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCIn(List<Double> values) {
            addCriterion("equi_ps_c in", values, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCNotIn(List<Double> values) {
            addCriterion("equi_ps_c not in", values, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCBetween(Double value1, Double value2) {
            addCriterion("equi_ps_c between", value1, value2, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiPsCNotBetween(Double value1, Double value2) {
            addCriterion("equi_ps_c not between", value1, value2, "equiPsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsIsNull() {
            addCriterion("equi_qs is null");
            return (Criteria) this;
        }

        public Criteria andEquiQsIsNotNull() {
            addCriterion("equi_qs is not null");
            return (Criteria) this;
        }

        public Criteria andEquiQsEqualTo(Double value) {
            addCriterion("equi_qs =", value, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsNotEqualTo(Double value) {
            addCriterion("equi_qs <>", value, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsGreaterThan(Double value) {
            addCriterion("equi_qs >", value, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_qs >=", value, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsLessThan(Double value) {
            addCriterion("equi_qs <", value, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsLessThanOrEqualTo(Double value) {
            addCriterion("equi_qs <=", value, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsIn(List<Double> values) {
            addCriterion("equi_qs in", values, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsNotIn(List<Double> values) {
            addCriterion("equi_qs not in", values, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsBetween(Double value1, Double value2) {
            addCriterion("equi_qs between", value1, value2, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsNotBetween(Double value1, Double value2) {
            addCriterion("equi_qs not between", value1, value2, "equiQs");
            return (Criteria) this;
        }

        public Criteria andEquiQsAIsNull() {
            addCriterion("equi_qs_a is null");
            return (Criteria) this;
        }

        public Criteria andEquiQsAIsNotNull() {
            addCriterion("equi_qs_a is not null");
            return (Criteria) this;
        }

        public Criteria andEquiQsAEqualTo(Double value) {
            addCriterion("equi_qs_a =", value, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsANotEqualTo(Double value) {
            addCriterion("equi_qs_a <>", value, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsAGreaterThan(Double value) {
            addCriterion("equi_qs_a >", value, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsAGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_qs_a >=", value, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsALessThan(Double value) {
            addCriterion("equi_qs_a <", value, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsALessThanOrEqualTo(Double value) {
            addCriterion("equi_qs_a <=", value, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsAIn(List<Double> values) {
            addCriterion("equi_qs_a in", values, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsANotIn(List<Double> values) {
            addCriterion("equi_qs_a not in", values, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsABetween(Double value1, Double value2) {
            addCriterion("equi_qs_a between", value1, value2, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsANotBetween(Double value1, Double value2) {
            addCriterion("equi_qs_a not between", value1, value2, "equiQsA");
            return (Criteria) this;
        }

        public Criteria andEquiQsBIsNull() {
            addCriterion("equi_qs_b is null");
            return (Criteria) this;
        }

        public Criteria andEquiQsBIsNotNull() {
            addCriterion("equi_qs_b is not null");
            return (Criteria) this;
        }

        public Criteria andEquiQsBEqualTo(Double value) {
            addCriterion("equi_qs_b =", value, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBNotEqualTo(Double value) {
            addCriterion("equi_qs_b <>", value, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBGreaterThan(Double value) {
            addCriterion("equi_qs_b >", value, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_qs_b >=", value, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBLessThan(Double value) {
            addCriterion("equi_qs_b <", value, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBLessThanOrEqualTo(Double value) {
            addCriterion("equi_qs_b <=", value, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBIn(List<Double> values) {
            addCriterion("equi_qs_b in", values, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBNotIn(List<Double> values) {
            addCriterion("equi_qs_b not in", values, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBBetween(Double value1, Double value2) {
            addCriterion("equi_qs_b between", value1, value2, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsBNotBetween(Double value1, Double value2) {
            addCriterion("equi_qs_b not between", value1, value2, "equiQsB");
            return (Criteria) this;
        }

        public Criteria andEquiQsCIsNull() {
            addCriterion("equi_qs_c is null");
            return (Criteria) this;
        }

        public Criteria andEquiQsCIsNotNull() {
            addCriterion("equi_qs_c is not null");
            return (Criteria) this;
        }

        public Criteria andEquiQsCEqualTo(Double value) {
            addCriterion("equi_qs_c =", value, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCNotEqualTo(Double value) {
            addCriterion("equi_qs_c <>", value, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCGreaterThan(Double value) {
            addCriterion("equi_qs_c >", value, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_qs_c >=", value, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCLessThan(Double value) {
            addCriterion("equi_qs_c <", value, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCLessThanOrEqualTo(Double value) {
            addCriterion("equi_qs_c <=", value, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCIn(List<Double> values) {
            addCriterion("equi_qs_c in", values, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCNotIn(List<Double> values) {
            addCriterion("equi_qs_c not in", values, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCBetween(Double value1, Double value2) {
            addCriterion("equi_qs_c between", value1, value2, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiQsCNotBetween(Double value1, Double value2) {
            addCriterion("equi_qs_c not between", value1, value2, "equiQsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsIsNull() {
            addCriterion("equi_pfs is null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsIsNotNull() {
            addCriterion("equi_pfs is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsEqualTo(Double value) {
            addCriterion("equi_pfs =", value, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsNotEqualTo(Double value) {
            addCriterion("equi_pfs <>", value, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsGreaterThan(Double value) {
            addCriterion("equi_pfs >", value, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_pfs >=", value, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsLessThan(Double value) {
            addCriterion("equi_pfs <", value, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsLessThanOrEqualTo(Double value) {
            addCriterion("equi_pfs <=", value, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsIn(List<Double> values) {
            addCriterion("equi_pfs in", values, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsNotIn(List<Double> values) {
            addCriterion("equi_pfs not in", values, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBetween(Double value1, Double value2) {
            addCriterion("equi_pfs between", value1, value2, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsNotBetween(Double value1, Double value2) {
            addCriterion("equi_pfs not between", value1, value2, "equiPfs");
            return (Criteria) this;
        }

        public Criteria andEquiPfsAIsNull() {
            addCriterion("equi_pfs_a is null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsAIsNotNull() {
            addCriterion("equi_pfs_a is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsAEqualTo(Double value) {
            addCriterion("equi_pfs_a =", value, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsANotEqualTo(Double value) {
            addCriterion("equi_pfs_a <>", value, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsAGreaterThan(Double value) {
            addCriterion("equi_pfs_a >", value, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsAGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_pfs_a >=", value, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsALessThan(Double value) {
            addCriterion("equi_pfs_a <", value, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsALessThanOrEqualTo(Double value) {
            addCriterion("equi_pfs_a <=", value, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsAIn(List<Double> values) {
            addCriterion("equi_pfs_a in", values, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsANotIn(List<Double> values) {
            addCriterion("equi_pfs_a not in", values, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsABetween(Double value1, Double value2) {
            addCriterion("equi_pfs_a between", value1, value2, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsANotBetween(Double value1, Double value2) {
            addCriterion("equi_pfs_a not between", value1, value2, "equiPfsA");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBIsNull() {
            addCriterion("equi_pfs_b is null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBIsNotNull() {
            addCriterion("equi_pfs_b is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBEqualTo(Double value) {
            addCriterion("equi_pfs_b =", value, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBNotEqualTo(Double value) {
            addCriterion("equi_pfs_b <>", value, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBGreaterThan(Double value) {
            addCriterion("equi_pfs_b >", value, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_pfs_b >=", value, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBLessThan(Double value) {
            addCriterion("equi_pfs_b <", value, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBLessThanOrEqualTo(Double value) {
            addCriterion("equi_pfs_b <=", value, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBIn(List<Double> values) {
            addCriterion("equi_pfs_b in", values, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBNotIn(List<Double> values) {
            addCriterion("equi_pfs_b not in", values, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBBetween(Double value1, Double value2) {
            addCriterion("equi_pfs_b between", value1, value2, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsBNotBetween(Double value1, Double value2) {
            addCriterion("equi_pfs_b not between", value1, value2, "equiPfsB");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCIsNull() {
            addCriterion("equi_pfs_c is null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCIsNotNull() {
            addCriterion("equi_pfs_c is not null");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCEqualTo(Double value) {
            addCriterion("equi_pfs_c =", value, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCNotEqualTo(Double value) {
            addCriterion("equi_pfs_c <>", value, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCGreaterThan(Double value) {
            addCriterion("equi_pfs_c >", value, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_pfs_c >=", value, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCLessThan(Double value) {
            addCriterion("equi_pfs_c <", value, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCLessThanOrEqualTo(Double value) {
            addCriterion("equi_pfs_c <=", value, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCIn(List<Double> values) {
            addCriterion("equi_pfs_c in", values, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCNotIn(List<Double> values) {
            addCriterion("equi_pfs_c not in", values, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCBetween(Double value1, Double value2) {
            addCriterion("equi_pfs_c between", value1, value2, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiPfsCNotBetween(Double value1, Double value2) {
            addCriterion("equi_pfs_c not between", value1, value2, "equiPfsC");
            return (Criteria) this;
        }

        public Criteria andEquiUaIsNull() {
            addCriterion("equi_ua is null");
            return (Criteria) this;
        }

        public Criteria andEquiUaIsNotNull() {
            addCriterion("equi_ua is not null");
            return (Criteria) this;
        }

        public Criteria andEquiUaEqualTo(Double value) {
            addCriterion("equi_ua =", value, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaNotEqualTo(Double value) {
            addCriterion("equi_ua <>", value, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaGreaterThan(Double value) {
            addCriterion("equi_ua >", value, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ua >=", value, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaLessThan(Double value) {
            addCriterion("equi_ua <", value, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaLessThanOrEqualTo(Double value) {
            addCriterion("equi_ua <=", value, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaIn(List<Double> values) {
            addCriterion("equi_ua in", values, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaNotIn(List<Double> values) {
            addCriterion("equi_ua not in", values, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaBetween(Double value1, Double value2) {
            addCriterion("equi_ua between", value1, value2, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUaNotBetween(Double value1, Double value2) {
            addCriterion("equi_ua not between", value1, value2, "equiUa");
            return (Criteria) this;
        }

        public Criteria andEquiUbIsNull() {
            addCriterion("equi_ub is null");
            return (Criteria) this;
        }

        public Criteria andEquiUbIsNotNull() {
            addCriterion("equi_ub is not null");
            return (Criteria) this;
        }

        public Criteria andEquiUbEqualTo(Double value) {
            addCriterion("equi_ub =", value, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbNotEqualTo(Double value) {
            addCriterion("equi_ub <>", value, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbGreaterThan(Double value) {
            addCriterion("equi_ub >", value, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ub >=", value, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbLessThan(Double value) {
            addCriterion("equi_ub <", value, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbLessThanOrEqualTo(Double value) {
            addCriterion("equi_ub <=", value, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbIn(List<Double> values) {
            addCriterion("equi_ub in", values, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbNotIn(List<Double> values) {
            addCriterion("equi_ub not in", values, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbBetween(Double value1, Double value2) {
            addCriterion("equi_ub between", value1, value2, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUbNotBetween(Double value1, Double value2) {
            addCriterion("equi_ub not between", value1, value2, "equiUb");
            return (Criteria) this;
        }

        public Criteria andEquiUcIsNull() {
            addCriterion("equi_uc is null");
            return (Criteria) this;
        }

        public Criteria andEquiUcIsNotNull() {
            addCriterion("equi_uc is not null");
            return (Criteria) this;
        }

        public Criteria andEquiUcEqualTo(Double value) {
            addCriterion("equi_uc =", value, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcNotEqualTo(Double value) {
            addCriterion("equi_uc <>", value, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcGreaterThan(Double value) {
            addCriterion("equi_uc >", value, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_uc >=", value, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcLessThan(Double value) {
            addCriterion("equi_uc <", value, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcLessThanOrEqualTo(Double value) {
            addCriterion("equi_uc <=", value, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcIn(List<Double> values) {
            addCriterion("equi_uc in", values, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcNotIn(List<Double> values) {
            addCriterion("equi_uc not in", values, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcBetween(Double value1, Double value2) {
            addCriterion("equi_uc between", value1, value2, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUcNotBetween(Double value1, Double value2) {
            addCriterion("equi_uc not between", value1, value2, "equiUc");
            return (Criteria) this;
        }

        public Criteria andEquiUabIsNull() {
            addCriterion("equi_uab is null");
            return (Criteria) this;
        }

        public Criteria andEquiUabIsNotNull() {
            addCriterion("equi_uab is not null");
            return (Criteria) this;
        }

        public Criteria andEquiUabEqualTo(Double value) {
            addCriterion("equi_uab =", value, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabNotEqualTo(Double value) {
            addCriterion("equi_uab <>", value, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabGreaterThan(Double value) {
            addCriterion("equi_uab >", value, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_uab >=", value, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabLessThan(Double value) {
            addCriterion("equi_uab <", value, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabLessThanOrEqualTo(Double value) {
            addCriterion("equi_uab <=", value, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabIn(List<Double> values) {
            addCriterion("equi_uab in", values, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabNotIn(List<Double> values) {
            addCriterion("equi_uab not in", values, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabBetween(Double value1, Double value2) {
            addCriterion("equi_uab between", value1, value2, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUabNotBetween(Double value1, Double value2) {
            addCriterion("equi_uab not between", value1, value2, "equiUab");
            return (Criteria) this;
        }

        public Criteria andEquiUbcIsNull() {
            addCriterion("equi_ubc is null");
            return (Criteria) this;
        }

        public Criteria andEquiUbcIsNotNull() {
            addCriterion("equi_ubc is not null");
            return (Criteria) this;
        }

        public Criteria andEquiUbcEqualTo(Double value) {
            addCriterion("equi_ubc =", value, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcNotEqualTo(Double value) {
            addCriterion("equi_ubc <>", value, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcGreaterThan(Double value) {
            addCriterion("equi_ubc >", value, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ubc >=", value, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcLessThan(Double value) {
            addCriterion("equi_ubc <", value, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcLessThanOrEqualTo(Double value) {
            addCriterion("equi_ubc <=", value, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcIn(List<Double> values) {
            addCriterion("equi_ubc in", values, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcNotIn(List<Double> values) {
            addCriterion("equi_ubc not in", values, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcBetween(Double value1, Double value2) {
            addCriterion("equi_ubc between", value1, value2, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUbcNotBetween(Double value1, Double value2) {
            addCriterion("equi_ubc not between", value1, value2, "equiUbc");
            return (Criteria) this;
        }

        public Criteria andEquiUcaIsNull() {
            addCriterion("equi_uca is null");
            return (Criteria) this;
        }

        public Criteria andEquiUcaIsNotNull() {
            addCriterion("equi_uca is not null");
            return (Criteria) this;
        }

        public Criteria andEquiUcaEqualTo(Double value) {
            addCriterion("equi_uca =", value, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaNotEqualTo(Double value) {
            addCriterion("equi_uca <>", value, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaGreaterThan(Double value) {
            addCriterion("equi_uca >", value, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_uca >=", value, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaLessThan(Double value) {
            addCriterion("equi_uca <", value, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaLessThanOrEqualTo(Double value) {
            addCriterion("equi_uca <=", value, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaIn(List<Double> values) {
            addCriterion("equi_uca in", values, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaNotIn(List<Double> values) {
            addCriterion("equi_uca not in", values, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaBetween(Double value1, Double value2) {
            addCriterion("equi_uca between", value1, value2, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiUcaNotBetween(Double value1, Double value2) {
            addCriterion("equi_uca not between", value1, value2, "equiUca");
            return (Criteria) this;
        }

        public Criteria andEquiIaIsNull() {
            addCriterion("equi_ia is null");
            return (Criteria) this;
        }

        public Criteria andEquiIaIsNotNull() {
            addCriterion("equi_ia is not null");
            return (Criteria) this;
        }

        public Criteria andEquiIaEqualTo(Double value) {
            addCriterion("equi_ia =", value, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaNotEqualTo(Double value) {
            addCriterion("equi_ia <>", value, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaGreaterThan(Double value) {
            addCriterion("equi_ia >", value, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ia >=", value, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaLessThan(Double value) {
            addCriterion("equi_ia <", value, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaLessThanOrEqualTo(Double value) {
            addCriterion("equi_ia <=", value, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaIn(List<Double> values) {
            addCriterion("equi_ia in", values, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaNotIn(List<Double> values) {
            addCriterion("equi_ia not in", values, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaBetween(Double value1, Double value2) {
            addCriterion("equi_ia between", value1, value2, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIaNotBetween(Double value1, Double value2) {
            addCriterion("equi_ia not between", value1, value2, "equiIa");
            return (Criteria) this;
        }

        public Criteria andEquiIbIsNull() {
            addCriterion("equi_ib is null");
            return (Criteria) this;
        }

        public Criteria andEquiIbIsNotNull() {
            addCriterion("equi_ib is not null");
            return (Criteria) this;
        }

        public Criteria andEquiIbEqualTo(Double value) {
            addCriterion("equi_ib =", value, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbNotEqualTo(Double value) {
            addCriterion("equi_ib <>", value, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbGreaterThan(Double value) {
            addCriterion("equi_ib >", value, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ib >=", value, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbLessThan(Double value) {
            addCriterion("equi_ib <", value, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbLessThanOrEqualTo(Double value) {
            addCriterion("equi_ib <=", value, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbIn(List<Double> values) {
            addCriterion("equi_ib in", values, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbNotIn(List<Double> values) {
            addCriterion("equi_ib not in", values, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbBetween(Double value1, Double value2) {
            addCriterion("equi_ib between", value1, value2, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIbNotBetween(Double value1, Double value2) {
            addCriterion("equi_ib not between", value1, value2, "equiIb");
            return (Criteria) this;
        }

        public Criteria andEquiIcIsNull() {
            addCriterion("equi_ic is null");
            return (Criteria) this;
        }

        public Criteria andEquiIcIsNotNull() {
            addCriterion("equi_ic is not null");
            return (Criteria) this;
        }

        public Criteria andEquiIcEqualTo(Double value) {
            addCriterion("equi_ic =", value, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcNotEqualTo(Double value) {
            addCriterion("equi_ic <>", value, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcGreaterThan(Double value) {
            addCriterion("equi_ic >", value, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_ic >=", value, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcLessThan(Double value) {
            addCriterion("equi_ic <", value, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcLessThanOrEqualTo(Double value) {
            addCriterion("equi_ic <=", value, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcIn(List<Double> values) {
            addCriterion("equi_ic in", values, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcNotIn(List<Double> values) {
            addCriterion("equi_ic not in", values, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcBetween(Double value1, Double value2) {
            addCriterion("equi_ic between", value1, value2, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiIcNotBetween(Double value1, Double value2) {
            addCriterion("equi_ic not between", value1, value2, "equiIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaIsNull() {
            addCriterion("equi_thd_ia is null");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaIsNotNull() {
            addCriterion("equi_thd_ia is not null");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaEqualTo(Double value) {
            addCriterion("equi_thd_ia =", value, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaNotEqualTo(Double value) {
            addCriterion("equi_thd_ia <>", value, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaGreaterThan(Double value) {
            addCriterion("equi_thd_ia >", value, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ia >=", value, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaLessThan(Double value) {
            addCriterion("equi_thd_ia <", value, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaLessThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ia <=", value, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaIn(List<Double> values) {
            addCriterion("equi_thd_ia in", values, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaNotIn(List<Double> values) {
            addCriterion("equi_thd_ia not in", values, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ia between", value1, value2, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIaNotBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ia not between", value1, value2, "equiThdIa");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbIsNull() {
            addCriterion("equi_thd_ib is null");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbIsNotNull() {
            addCriterion("equi_thd_ib is not null");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbEqualTo(Double value) {
            addCriterion("equi_thd_ib =", value, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbNotEqualTo(Double value) {
            addCriterion("equi_thd_ib <>", value, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbGreaterThan(Double value) {
            addCriterion("equi_thd_ib >", value, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ib >=", value, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbLessThan(Double value) {
            addCriterion("equi_thd_ib <", value, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbLessThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ib <=", value, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbIn(List<Double> values) {
            addCriterion("equi_thd_ib in", values, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbNotIn(List<Double> values) {
            addCriterion("equi_thd_ib not in", values, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ib between", value1, value2, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIbNotBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ib not between", value1, value2, "equiThdIb");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcIsNull() {
            addCriterion("equi_thd_ic is null");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcIsNotNull() {
            addCriterion("equi_thd_ic is not null");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcEqualTo(Double value) {
            addCriterion("equi_thd_ic =", value, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcNotEqualTo(Double value) {
            addCriterion("equi_thd_ic <>", value, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcGreaterThan(Double value) {
            addCriterion("equi_thd_ic >", value, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ic >=", value, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcLessThan(Double value) {
            addCriterion("equi_thd_ic <", value, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcLessThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ic <=", value, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcIn(List<Double> values) {
            addCriterion("equi_thd_ic in", values, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcNotIn(List<Double> values) {
            addCriterion("equi_thd_ic not in", values, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ic between", value1, value2, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdIcNotBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ic not between", value1, value2, "equiThdIc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaIsNull() {
            addCriterion("equi_thd_ua is null");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaIsNotNull() {
            addCriterion("equi_thd_ua is not null");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaEqualTo(Double value) {
            addCriterion("equi_thd_ua =", value, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaNotEqualTo(Double value) {
            addCriterion("equi_thd_ua <>", value, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaGreaterThan(Double value) {
            addCriterion("equi_thd_ua >", value, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ua >=", value, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaLessThan(Double value) {
            addCriterion("equi_thd_ua <", value, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaLessThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ua <=", value, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaIn(List<Double> values) {
            addCriterion("equi_thd_ua in", values, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaNotIn(List<Double> values) {
            addCriterion("equi_thd_ua not in", values, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ua between", value1, value2, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUaNotBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ua not between", value1, value2, "equiThdUa");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbIsNull() {
            addCriterion("equi_thd_ub is null");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbIsNotNull() {
            addCriterion("equi_thd_ub is not null");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbEqualTo(Double value) {
            addCriterion("equi_thd_ub =", value, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbNotEqualTo(Double value) {
            addCriterion("equi_thd_ub <>", value, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbGreaterThan(Double value) {
            addCriterion("equi_thd_ub >", value, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ub >=", value, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbLessThan(Double value) {
            addCriterion("equi_thd_ub <", value, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbLessThanOrEqualTo(Double value) {
            addCriterion("equi_thd_ub <=", value, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbIn(List<Double> values) {
            addCriterion("equi_thd_ub in", values, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbNotIn(List<Double> values) {
            addCriterion("equi_thd_ub not in", values, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ub between", value1, value2, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUbNotBetween(Double value1, Double value2) {
            addCriterion("equi_thd_ub not between", value1, value2, "equiThdUb");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcIsNull() {
            addCriterion("equi_thd_uc is null");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcIsNotNull() {
            addCriterion("equi_thd_uc is not null");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcEqualTo(Double value) {
            addCriterion("equi_thd_uc =", value, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcNotEqualTo(Double value) {
            addCriterion("equi_thd_uc <>", value, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcGreaterThan(Double value) {
            addCriterion("equi_thd_uc >", value, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcGreaterThanOrEqualTo(Double value) {
            addCriterion("equi_thd_uc >=", value, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcLessThan(Double value) {
            addCriterion("equi_thd_uc <", value, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcLessThanOrEqualTo(Double value) {
            addCriterion("equi_thd_uc <=", value, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcIn(List<Double> values) {
            addCriterion("equi_thd_uc in", values, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcNotIn(List<Double> values) {
            addCriterion("equi_thd_uc not in", values, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcBetween(Double value1, Double value2) {
            addCriterion("equi_thd_uc between", value1, value2, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andEquiThdUcNotBetween(Double value1, Double value2) {
            addCriterion("equi_thd_uc not between", value1, value2, "equiThdUc");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIsNull() {
            addCriterion("collect_time is null");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIsNotNull() {
            addCriterion("collect_time is not null");
            return (Criteria) this;
        }

        public Criteria andCollectTimeEqualTo(Date value) {
            addCriterion("collect_time =", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotEqualTo(Date value) {
            addCriterion("collect_time <>", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeGreaterThan(Date value) {
            addCriterion("collect_time >", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("collect_time >=", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeLessThan(Date value) {
            addCriterion("collect_time <", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeLessThanOrEqualTo(Date value) {
            addCriterion("collect_time <=", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIn(List<Date> values) {
            addCriterion("collect_time in", values, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotIn(List<Date> values) {
            addCriterion("collect_time not in", values, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeBetween(Date value1, Date value2) {
            addCriterion("collect_time between", value1, value2, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotBetween(Date value1, Date value2) {
            addCriterion("collect_time not between", value1, value2, "collectTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeIsNull() {
            addCriterion("save_time is null");
            return (Criteria) this;
        }

        public Criteria andSaveTimeIsNotNull() {
            addCriterion("save_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaveTimeEqualTo(Date value) {
            addCriterion("save_time =", value, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeNotEqualTo(Date value) {
            addCriterion("save_time <>", value, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeGreaterThan(Date value) {
            addCriterion("save_time >", value, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("save_time >=", value, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeLessThan(Date value) {
            addCriterion("save_time <", value, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeLessThanOrEqualTo(Date value) {
            addCriterion("save_time <=", value, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeIn(List<Date> values) {
            addCriterion("save_time in", values, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeNotIn(List<Date> values) {
            addCriterion("save_time not in", values, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeBetween(Date value1, Date value2) {
            addCriterion("save_time between", value1, value2, "saveTime");
            return (Criteria) this;
        }

        public Criteria andSaveTimeNotBetween(Date value1, Date value2) {
            addCriterion("save_time not between", value1, value2, "saveTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 31 17:56:21 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table power_cdmeterdata_realtime
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}