package com.chinadovey.power.webapps.pojo;

import java.util.Date;

public class PowerCdmeterdataRealtimeSingle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Integer ecuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Long equiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Integer equiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_fr
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiFr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_ps
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_qs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiQs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_pfs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiPfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_u
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.equi_i
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_realtime_s.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Date saveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.id
     *
     * @return the value of power_cdmeterdata_realtime_s.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.id
     *
     * @param id the value for power_cdmeterdata_realtime_s.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.ecu_id
     *
     * @return the value of power_cdmeterdata_realtime_s.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Integer getEcuId() {
        return ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.ecu_id
     *
     * @param ecuId the value for power_cdmeterdata_realtime_s.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEcuId(Integer ecuId) {
        this.ecuId = ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_id
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Long getEquiId() {
        return equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_id
     *
     * @param equiId the value for power_cdmeterdata_realtime_s.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiId(Long equiId) {
        this.equiId = equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_status
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Integer getEquiStatus() {
        return equiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_status
     *
     * @param equiStatus the value for power_cdmeterdata_realtime_s.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiStatus(Integer equiStatus) {
        this.equiStatus = equiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_fr
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_fr
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiFr() {
        return equiFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_fr
     *
     * @param equiFr the value for power_cdmeterdata_realtime_s.equi_fr
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiFr(Double equiFr) {
        this.equiFr = equiFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_ps
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_ps
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPs() {
        return equiPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_ps
     *
     * @param equiPs the value for power_cdmeterdata_realtime_s.equi_ps
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPs(Double equiPs) {
        this.equiPs = equiPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_qs
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_qs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiQs() {
        return equiQs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_qs
     *
     * @param equiQs the value for power_cdmeterdata_realtime_s.equi_qs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiQs(Double equiQs) {
        this.equiQs = equiQs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_pfs
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_pfs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiPfs() {
        return equiPfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_pfs
     *
     * @param equiPfs the value for power_cdmeterdata_realtime_s.equi_pfs
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiPfs(Double equiPfs) {
        this.equiPfs = equiPfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_u
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_u
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiU() {
        return equiU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_u
     *
     * @param equiU the value for power_cdmeterdata_realtime_s.equi_u
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiU(Double equiU) {
        this.equiU = equiU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.equi_i
     *
     * @return the value of power_cdmeterdata_realtime_s.equi_i
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiI() {
        return equiI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.equi_i
     *
     * @param equiI the value for power_cdmeterdata_realtime_s.equi_i
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiI(Double equiI) {
        this.equiI = equiI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.collect_time
     *
     * @return the value of power_cdmeterdata_realtime_s.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.collect_time
     *
     * @param collectTime the value for power_cdmeterdata_realtime_s.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_realtime_s.save_time
     *
     * @return the value of power_cdmeterdata_realtime_s.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_realtime_s.save_time
     *
     * @param saveTime the value for power_cdmeterdata_realtime_s.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }
}