package com.chinadovey.power.webapps.pojo;

import java.util.Date;

public class PowerCdmeterdataTotalSingle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Integer ecuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Long equiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Integer equiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_tee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiTee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_tsee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiTsee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_thee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiThee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_tnee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiTnee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_tlee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiTlee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_wpp
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiWpp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.equi_wqp
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Double equiWqp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_cdmeterdata_total_s.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    private Date saveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.id
     *
     * @return the value of power_cdmeterdata_total_s.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.id
     *
     * @param id the value for power_cdmeterdata_total_s.id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.ecu_id
     *
     * @return the value of power_cdmeterdata_total_s.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Integer getEcuId() {
        return ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.ecu_id
     *
     * @param ecuId the value for power_cdmeterdata_total_s.ecu_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEcuId(Integer ecuId) {
        this.ecuId = ecuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_id
     *
     * @return the value of power_cdmeterdata_total_s.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Long getEquiId() {
        return equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_id
     *
     * @param equiId the value for power_cdmeterdata_total_s.equi_id
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiId(Long equiId) {
        this.equiId = equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_status
     *
     * @return the value of power_cdmeterdata_total_s.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Integer getEquiStatus() {
        return equiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_status
     *
     * @param equiStatus the value for power_cdmeterdata_total_s.equi_status
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiStatus(Integer equiStatus) {
        this.equiStatus = equiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_tee
     *
     * @return the value of power_cdmeterdata_total_s.equi_tee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiTee() {
        return equiTee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_tee
     *
     * @param equiTee the value for power_cdmeterdata_total_s.equi_tee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiTee(Double equiTee) {
        this.equiTee = equiTee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_tsee
     *
     * @return the value of power_cdmeterdata_total_s.equi_tsee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiTsee() {
        return equiTsee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_tsee
     *
     * @param equiTsee the value for power_cdmeterdata_total_s.equi_tsee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiTsee(Double equiTsee) {
        this.equiTsee = equiTsee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_thee
     *
     * @return the value of power_cdmeterdata_total_s.equi_thee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiThee() {
        return equiThee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_thee
     *
     * @param equiThee the value for power_cdmeterdata_total_s.equi_thee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiThee(Double equiThee) {
        this.equiThee = equiThee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_tnee
     *
     * @return the value of power_cdmeterdata_total_s.equi_tnee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiTnee() {
        return equiTnee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_tnee
     *
     * @param equiTnee the value for power_cdmeterdata_total_s.equi_tnee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiTnee(Double equiTnee) {
        this.equiTnee = equiTnee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_tlee
     *
     * @return the value of power_cdmeterdata_total_s.equi_tlee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiTlee() {
        return equiTlee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_tlee
     *
     * @param equiTlee the value for power_cdmeterdata_total_s.equi_tlee
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiTlee(Double equiTlee) {
        this.equiTlee = equiTlee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_wpp
     *
     * @return the value of power_cdmeterdata_total_s.equi_wpp
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiWpp() {
        return equiWpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_wpp
     *
     * @param equiWpp the value for power_cdmeterdata_total_s.equi_wpp
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiWpp(Double equiWpp) {
        this.equiWpp = equiWpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.equi_wqp
     *
     * @return the value of power_cdmeterdata_total_s.equi_wqp
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Double getEquiWqp() {
        return equiWqp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.equi_wqp
     *
     * @param equiWqp the value for power_cdmeterdata_total_s.equi_wqp
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setEquiWqp(Double equiWqp) {
        this.equiWqp = equiWqp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.collect_time
     *
     * @return the value of power_cdmeterdata_total_s.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.collect_time
     *
     * @param collectTime the value for power_cdmeterdata_total_s.collect_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_cdmeterdata_total_s.save_time
     *
     * @return the value of power_cdmeterdata_total_s.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_cdmeterdata_total_s.save_time
     *
     * @param saveTime the value for power_cdmeterdata_total_s.save_time
     *
     * @mbggenerated Mon Oct 31 17:56:21 CST 2016
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }
}